/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skypedust.ui;

import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import com.skypedust.useraccount.XmlConfs;
import com.skypedust.useraccount.UserAccount;

/**
 *
 * @author gkatzioura
 */
public class SkypeDustApp extends javax.swing.JFrame {

    /**
     * Creates new form SkypeDustApp
     */
    public SkypeDustApp() {
        initComponents();
        userAccount = new UserAccount();
        if(!userAccount.userSettings.isEmpty()){
            usernameTextField.setText(userAccount.userSettings.get(XmlConfs.usernametag).toString());
            nicknameTextField.setText(userAccount.userSettings.get(XmlConfs.nicknametag).toString());
            passwordPasswordField.setText(userAccount.userSettings.get(XmlConfs.passwordtag).toString());
        }
        userAccount.initSaccount(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        skypeAccountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nicknameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        skypeFriendPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        model = new DefaultListModel();
        contactsjList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        concommandsjList = new javax.swing.JList();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        skypeMenu = new javax.swing.JMenu();
        skypeAccountItem = new javax.swing.JMenuItem();
        skypefriendsItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Skype Username");

        usernameTextField.setText("Your Username");

        jLabel2.setText("Nickname Displayed");

        nicknameTextField.setText("Your Nickname");

        jLabel3.setText("Password");

        passwordPasswordField.setText("jPasswordField1");

        jButton1.setText("Save Settings");

        javax.swing.GroupLayout skypeAccountPanelLayout = new javax.swing.GroupLayout(skypeAccountPanel);
        skypeAccountPanel.setLayout(skypeAccountPanelLayout);
        skypeAccountPanelLayout.setHorizontalGroup(
            skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skypeAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(skypeAccountPanelLayout.createSequentialGroup()
                        .addGroup(skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTextField)
                            .addComponent(nicknameTextField)
                            .addComponent(passwordPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, skypeAccountPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        skypeAccountPanelLayout.setVerticalGroup(
            skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skypeAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(skypeAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        mainPanel.add(skypeAccountPanel, "card2");

        jLabel4.setText("Contacts");

        jLabel5.setText("Allowed to issue commands");

        jLabel6.setText("Add Contact");

        contactTextField.setText("Skype Contact");

        jButton2.setText("Add");

        jLabel7.setText("Drag and Drop to allow Contacts ");

        jLabel8.setText("to issue commands");

        contactsjList.setModel(model);
        jScrollPane1.setViewportView(contactsjList);

        concommandsjList.setModel(model);
        jScrollPane2.setViewportView(concommandsjList);

        javax.swing.GroupLayout skypeFriendPanelLayout = new javax.swing.GroupLayout(skypeFriendPanel);
        skypeFriendPanel.setLayout(skypeFriendPanelLayout);
        skypeFriendPanelLayout.setHorizontalGroup(
            skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skypeFriendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(skypeFriendPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(21, 21, 21))
        );
        skypeFriendPanelLayout.setVerticalGroup(
            skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skypeFriendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skypeFriendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel8))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        mainPanel.add(skypeFriendPanel, "card3");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        skypeMenu.setMnemonic('e');
        skypeMenu.setText("Skype");

        skypeAccountItem.setText("Your Skype Account");
        skypeMenu.add(skypeAccountItem);

        skypefriendsItem.setText("Skype Friends");
        skypefriendsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skypefriendsItemActionPerformed(evt);
            }
        });
        skypeMenu.add(skypefriendsItem);

        jMenuItem1.setText("Chat Commands Center");
        skypeMenu.add(jMenuItem1);

        menuBar.add(skypeMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JDialog about = new SkypeDustAboutBox(this, rootPaneCheckingEnabled);
        about.show();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void skypefriendsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skypefriendsItemActionPerformed
        cardSwitcher("card3");
    }//GEN-LAST:event_skypefriendsItemActionPerformed

    private void cardSwitcher(String card){
        CardLayout cardLayout = (CardLayout)(mainPanel.getLayout());
        cardLayout.show(mainPanel,card);
    }
    
    public void setContactList(String[] constring){

        model = new DefaultListModel();
        for(String i:constring)
            model.addElement(i);
        contactsjList.setModel(model);
        jScrollPane1.getViewport().setView(contactsjList);
            
    }

    public void setAllowedList(String[] allowedstring){
    
        System.out.println("set Allowed Contacts List");
        model = new DefaultListModel();
        for(String i:allowedstring)
            model.addElement(i);
        
        concommandsjList.setModel(model);
        jScrollPane2.getViewport().setView(concommandsjList);
        
    }    
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JList concommandsjList;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JList contactsjList;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField nicknameTextField;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JMenuItem skypeAccountItem;
    private javax.swing.JPanel skypeAccountPanel;
    private javax.swing.JPanel skypeFriendPanel;
    private javax.swing.JMenu skypeMenu;
    private javax.swing.JMenuItem skypefriendsItem;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
    private UserAccount userAccount;
    private ConlistHandler conlistHandler = new ConlistHandler();
    private DefaultListModel model = new DefaultListModel();
}
